services:
  credit_invoice:
    container_name: credit_invoice
    build:
      context: .
      dockerfile: ./credit-invoice/Dockerfile
    ports:
      - "8080:80"
    environment:
      - AWS_ENDPOINT=http://localstack:4566
      - AWS_REGION=us-east-1
      - AWS_LOGIN=test
      - AWS_PASS=test
      - AWS_CUSTOMERS_TABLE_NAME=local-customers-table
      - AWS_TRANSACTIONS_TABLE_NAME=local-transactions-table
      - AWS_PURCHASES_QUEUE_NAME=local-purchases-queue
      - CORE_BANKING_HOST=http://core_banking_mock
    volumes:
      - ./credit-invoice/src:/home/credit-invoice/src
      - ./commons:/home/commons
  core_banking_mock:
    container_name: core_banking_mock
    build:
      context: .
      dockerfile: ./core-banking-mock/Dockerfile
    ports:
      - "9090:80"
    environment:
      - AWS_ENDPOINT=http://localstack:4566
      - AWS_REGION=us-east-1
      - AWS_LOGIN=test
      - AWS_PASS=test
      - AWS_PURCHASES_QUEUE_NAME=local-purchases-queue
    volumes:
      - ./core-banking-mock/src:/home/core-banking-mock/src
      - ./commons:/home/commons
  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - LS_LOG=error
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$PWD/resources/script/init.sh:/etc/localstack/init/ready.d/init.sh"