services:
  credit_invoice:
    build: ./credit-invoice
    ports:
      - "8096:80"
  core_banking_mock:
    build: ./core-banking-mock
    ports:
      - "8080:80"
  producer_mock:
    build: ./producer-mock
  rabbitmq:
    image: rabbitmq:3.12