services:
  credit_invoice:
    build: ./credit-invoice
    ports:
      - "8096:80"
    volumes:
      - ./credit-invoice/src:/home/src
  core_banking_mock:
    build: ./core-banking-mock
    ports:
      - "8080:80"
    volumes:
      - ./core-banking-mock/src:/home/src
  producer_mock:
    build: ./producer-mock
    ports:
      - "9090:80"
    volumes:
      - ./producer-mock/src:/home/src
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - LS_LOG=error
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$PWD/script/init.sh:/etc/localstack/init/ready.d/init.sh"