services:
  credit_invoice:
    build: ./credit-invoice
    ports:
      - "8096:80"
  core_banking_mock:
    build: ./core-banking-mock
    ports:
      - "8080:80"
  producer_mock:
    build: ./producer-mock
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=credit_invoice
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "33060:3306"
    volumes:
      - mysql_vol:/var/lib/mysql
      - ./db-scripts:/docker-entrypoint-initdb.d
  rabbitmq:
    image: rabbitmq:3.12

volumes:
  mysql_vol: