services:
  credit_invoice:
    build:
      context: .
      dockerfile: ./credit-invoice/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./credit-invoice/src:/home/credit-invoice/src
      - ./commons:/home/commons
  core_banking_mock:
    build:
      context: .
      dockerfile: ./core-banking-mock/Dockerfile
    ports:
      - "9090:80"
    volumes:
      - ./core-banking-mock/src:/home/core-banking-mock/src
      - ./commons:/home/commons
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - LS_LOG=error
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$PWD/resources/script/init.sh:/etc/localstack/init/ready.d/init.sh"